# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test
env:
  BUILD_NUMBER: ${{ github.ref != 'refs/heads/main' && '' || github.run_number }}
  VERSION_NUMBER: ${{ vars.CURRENT_VERSION }}${{ github.ref == 'refs/heads/dev' && '-alpha.' || github.ref == 'refs/heads/release' && '-beta.' || '' }}

on:
  pull_request:
    branches: [ "dev", "release", "main" ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Kuchulem.DotNet.EntityAttributeValue.Converters/
    - name: Build
      run: dotnet build -p:VersionPrefix=$VERSION_NUMBER$BUILD_NUMBER --no-restore ./src/Kuchulem.DotNet.EntityAttributeValue.Converters/
    - name: Test
      run: dotnet test --verbosity normal ./tests/Kuchulem.DotNet.EntityAttributeValue.Converters.Tests/
